def Create_File(file_Name, discord, nome):
  file = open(file_Name, "w")
  file.write("-" * 20)
  file.write("\n")
  file.write("Discord: ")
  file.write(discord)
  file.write("\n")
  file.write("Nome: ")
  file.write(nome)
  file.write("\n")
  file.write("-" * 20)
  file.write("\n")
  file.close()


def Append_InFile(file_Name, ip_address, city, region, horario):
  filee = open(file_Name, "a")
  filee.write("-" * 20)
  filee.write("\n")
  filee.write("IP Address: ")
  filee.write(ip_address)
  filee.write("\n")
  filee.write("City: ")
  filee.write(city)
  filee.write("\n")
  filee.write("Estado/Regiao: ")
  filee.write(region)
  filee.write("\n")
  filee.write("Horario local: ")
  filee.write(horario)
  filee.write("\n")
  filee.write("-" * 20)
  filee.close()
